[package]
name = "json_int_rust_first"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-serialize = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
serde_derive = "*"
